# Generated by Django 2.1.1 on 2018-09-09 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone
import hotelweb.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrdersListView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AllOrdersListView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArrivalView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ArrivalsView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingSummaryView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'BookingSummaryView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CancellationView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'CancellationView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CleaningFacilityView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'CleaningFacilityView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CleaningRoomView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cleaningRoomView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartureView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DeparturesView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InhouseGuestView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'InhouseGuestsView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeastUsedFacilityView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'LeastUsedFacilityView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostUsedFacilityView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'MostUsedFacilityView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OverBookingView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'OverBookingsView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomsOccupiedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'RoomsOccupiedView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TodayBookingView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'TodayBookingView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', hotelweb.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type_id', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=700)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 864025, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('alert_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 864525, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 861876, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 861905, tzinfo=utc))),
                ('facility_type', models.CharField(max_length=50)),
                ('facility_id', models.CharField(max_length=50)),
                ('hotel_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('confirmation_number', models.CharField(max_length=100)),
                ('package_id', models.CharField(max_length=100)),
                ('booking_date', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 862063, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=700, null=True)),
                ('chat_type', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 861452, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('cleaning_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_id', models.CharField(max_length=50)),
                ('facility_type', models.CharField(max_length=50)),
                ('facility_id', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 858266, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('metric', models.CharField(help_text='can be Grams, Kg, Lb', max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 866097, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='DispatchStock',
            fields=[
                ('dispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('worker_id', models.CharField(max_length=100)),
                ('facility_id', models.EmailField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 873593, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('drink_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(help_text='can be in Litres, Boxes, Pieces', max_length=50)),
                ('metric', models.CharField(help_text='can be Grams, Kg, Lb', max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 865570, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 860777, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 860805, tzinfo=utc))),
                ('time', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 860845, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_number', models.CharField(max_length=50)),
                ('facility_name', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('facility_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 858787, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('facility_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_type', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 874529, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('metric', models.CharField(help_text='can be Grams, Kg, Lb', max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 865038, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 872971, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_ranking', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 870374, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('laundry_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('total_laundry_costs', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 871306, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='LaundryItems',
            fields=[
                ('laundry_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloth_type', models.CharField(max_length=100)),
                ('cloth_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LaundryType',
            fields=[
                ('laundry_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('clothe_type', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 872247, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('status', models.IntegerField(max_length=2)),
                ('status_time', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 868018, tzinfo=utc))),
                ('meal_time', models.CharField(help_text='Can be breakfast, lunch or dinner', max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 868094, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100)),
                ('menu_id', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 869232, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 868619, tzinfo=utc))),
                ('order_status', models.IntegerField(max_length=2)),
                ('paid', models.IntegerField(max_length=2)),
                ('created_by', models.IntegerField(default=0, max_length=2)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 868695, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 870831, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parking_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_location', models.CharField(max_length=100)),
                ('parking_slot_number', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 860254, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 859795, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('user_type_id', models.CharField(max_length=50)),
                ('request_type_id', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 862665, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('request_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 863575, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=10)),
                ('cleaning_status', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 857008, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 874084, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('supply_type', models.CharField(max_length=50)),
                ('supply_item', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 866650, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=50)),
                ('item_type', models.CharField(help_text='Can be food, drink or commodity', max_length=50)),
                ('supplier_id', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 867374, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('has_baby', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 856434, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='UserTrackingMovements',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('facility_id', models.CharField(max_length=100)),
                ('facility_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 869817, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 863135, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_plate', models.CharField(max_length=100)),
                ('owner_type', models.CharField(max_length=100)),
                ('user_id', models.CharField(help_text='User ID can be worker_id or user_id', max_length=100)),
                ('parking_id', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 859311, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('staff_id', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 9, 9, 19, 5, 6, 857732, tzinfo=utc))),
            ],
        ),
    ]
