# Generated by Django 2.0.6 on 2018-07-05 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=10)),
                ('cleaning_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('has_baby', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 7, 5, 15, 32, 13, 360683, tzinfo=utc))),
            ],
        ),
    ]
