# Generated by Django 2.1.1 on 2019-03-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshift',
            name='job_shift_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='job_title_status',
            field=models.IntegerField(default=1),
        ),
    ]
