# Generated by Django 2.0.7 on 2018-07-09 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotelweb', '0003_auto_20180705_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type_id', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('alert_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2018, 7, 9, 17, 13, 6, 395487, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2018, 7, 9, 17, 13, 6, 395522, tzinfo=utc))),
                ('facility_type', models.CharField(max_length=50)),
                ('facility_id', models.CharField(max_length=50)),
                ('hotel_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=700, null=True)),
                ('chat_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('cleaning_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_id', models.CharField(max_length=50)),
                ('facility_type', models.CharField(max_length=50)),
                ('facility_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('metric', models.CharField(help_text='can be Grams, Kg, Lb', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('drink_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(help_text='can be in Litres, Boxes, Pieces', max_length=50)),
                ('metric', models.CharField(help_text='can be Grams, Kg, Lb', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2018, 7, 9, 17, 13, 6, 394296, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2018, 7, 9, 17, 13, 6, 394338, tzinfo=utc))),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_number', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('facility_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('metric', models.CharField(help_text='can be Grams, Kg, Lb', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_ranking', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('status', models.IntegerField(max_length=2)),
                ('status_time', models.DateTimeField(default=datetime.datetime(2018, 7, 9, 17, 13, 6, 401405, tzinfo=utc))),
                ('meal_time', models.CharField(help_text='Can be breakfast, lunch or dinner', max_length=100)),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100)),
                ('menu_id', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(default=datetime.datetime(2018, 7, 9, 17, 13, 6, 402060, tzinfo=utc))),
                ('order_status', models.IntegerField(max_length=2)),
                ('paid', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parking_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_location', models.CharField(max_length=100)),
                ('parking_slot_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('user_type_id', models.CharField(max_length=50)),
                ('request_type_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('request_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('supply_type', models.CharField(max_length=50)),
                ('supply_item', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=50)),
                ('item_type', models.CharField(help_text='Can be food, drink or commodity', max_length=50)),
                ('supplier_id', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrackingMovements',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('facility_id', models.CharField(max_length=100)),
                ('facility_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_plate', models.CharField(max_length=100)),
                ('owner_type', models.CharField(max_length=100)),
                ('user_id', models.CharField(help_text='User ID can be worker_id or user_id', max_length=100)),
                ('parking_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('staff_id', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 17, 13, 6, 187648, tzinfo=utc)),
        ),
    ]
