# Generated by Django 2.0.7 on 2018-07-15 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotelweb', '0004_auto_20180709_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'My View',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchStock',
            fields=[
                ('dispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('worker_id', models.CharField(max_length=100)),
                ('facility_id', models.EmailField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('laundry_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('total_laundry_costs', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryType',
            fields=[
                ('laundry_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('clothe_type', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmation_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='package_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='status',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 12, 24, 4, 690961, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 12, 24, 4, 690925, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 12, 24, 4, 689854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 12, 24, 4, 689808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 12, 24, 4, 697818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 12, 24, 4, 698340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 12, 24, 4, 265096, tzinfo=utc)),
        ),
    ]
