# Generated by Django 2.1.1 on 2019-03-07 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotelweb', '0005_auto_20190307_0532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherFacility',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='facility_created_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='facility_cleaning_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_created_by',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_floor',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_number',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_facility',
        ),
        migrations.AddField(
            model_name='facility',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_capacity',
            field=models.CharField(default='something', max_length=50),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_location',
            field=models.CharField(default='something', max_length=50),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(default='something', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='room_created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='room_created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='room_floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default='something', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelweb.FacilityType'),
        ),
    ]
