# Generated by Django 2.0.7 on 2018-07-15 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotelweb', '0005_auto_20180715_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('facility_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_type', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 45670, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 45248, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='alerts',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 35109, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='alerttype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 35595, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 32535, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='chats',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 30345, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 26552, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='commodity',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 37480, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='dispatchstock',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 44776, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='drink',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 36867, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='events',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 29708, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='facilities',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 27287, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='food',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 36261, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='guests',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 44204, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 42005, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='laundry',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 43159, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='laundrytype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 43649, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='menu',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 39493, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 40689, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='orders',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 40120, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='packages',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 42577, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='parking',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 29068, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ratings',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 28537, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='requests',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 33378, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 34542, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='rooms',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 25067, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 38107, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='supplies',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 38751, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='usertrackingmovements',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 41275, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='usertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 33998, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 27922, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='workers',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 25893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 32272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 32224, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 29649, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 29614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 39405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 54, 40051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 19, 17, 51, 958578, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='arrivalsview',
            table='ArrivalsView',
        ),
    ]
