# Generated by Django 2.0.7 on 2018-07-21 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotelweb', '0006_auto_20180715_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ArrivalsView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingSummaryView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'BookingSummaryView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CancellationView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'CancellationView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartureView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DeparturesView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InhouseGuestView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'InhouseGuestsView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OverBookingView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'OverBookingsView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomsOccupiedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'RoomsOccupiedView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TodayBookingView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'TodayBookingView',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='facilities',
            name='facility_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertrackingmovements',
            name='status',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alerts',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 477843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 478431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 475804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 475581, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 475548, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 474943, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 470378, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 480161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dispatchstock',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 487223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='drink',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 479616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 473280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 473231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 473194, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 471083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facilitytype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 488433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 479023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guests',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 486651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 484440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 485636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='laundrytype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 486124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 482093, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 482007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 483154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 482645, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 482585, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 485069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 472655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 472173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 476479, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 477354, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 469084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 487746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 480733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 481397, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 16037, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertrackingmovements',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 483690, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 476925, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 471655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workers',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 23, 22, 29, 469796, tzinfo=utc)),
        ),
    ]
