# Generated by Django 2.0.6 on 2018-08-01 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotelweb', '0007_auto_20180721_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrdersListView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AllOrdersListView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeastUsedFacilityView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'LeastUsedFacilityView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostUsedFacilityView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'MostUsedFacilityView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaundryItems',
            fields=[
                ('laundry_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloth_type', models.CharField(max_length=100)),
                ('cloth_quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='created_by',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 710721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 711120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 708706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 707755, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 707726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 707323, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 704254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 712621, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dispatchstock',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 720793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='drink',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 712136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 706822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 706780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 706751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 704792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facilitytype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 721601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 711581, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guests',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 720291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 717988, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 718921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='laundrytype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 719803, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 714180, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 714100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 715449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 714867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 714794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 718486, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 706313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 705869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 709325, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 710288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 702946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 721223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 713134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 713635, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 674901, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertrackingmovements',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 717330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 709829, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 705393, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workers',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 8, 21, 33, 703563, tzinfo=utc)),
        ),
    ]
